server:
  port: 8769

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
        routes:
          - id: provide
            uri: http://localhost:8768
            predicates:
              - Path=/{path}

